name: Deploy Discord Bot

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: "Check if secrets are loaded"
        run: |
          if [ -z "${{ secrets.DROPLET_IP }}" ]; then
            echo "DROPLET_IP secret is NOT set!"
          else
            echo "DROPLET_IP secret is set."
          fi
          if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
            echo "SSH_PRIVATE_KEY secret is NOT set!"
          else
            echo "SSH_PRIVATE_KEY secret is set."
          fi
          if [ -z "${{ secrets.SSH_PASSPHRASE }}" ]; then
            echo "SSH_PASSPHRASE secret is NOT set (this is ok if your key has no passphrase)."
          else
            echo "SSH_PASSPHRASE secret is set."
          fi
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /root/lms-discord-bot

            git pull origin main

            python3 -m venv venv

            source venv/bin/activate
            pip install -r requirements.txt

            sudo systemctl restart discord-bot.service
